/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoluo_ndktest_testjni_MyJNI */

#ifndef _Included_com_xiaoluo_ndktest_testjni_MyJNI
#define _Included_com_xiaoluo_ndktest_testjni_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoluo_ndktest_testjni_MyJNI
 * Method:    sayhello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaoluo_ndktest_testjni_MyJNI_sayhello

  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
