//
// Created by Micheal on 2016/12/28.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class com_xiaoluo_ndktest_testjni_MyJNI */

#ifndef _Included_com_xiaoluo_ndktest_testjni_MyJNI
#define _Included_com_xiaoluo_ndktest_testjni_MyJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoluo_ndktest_testjni_MyJNI
 * Method:    sayhello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstringJNICALL Java_com_xiaoluo_ndktest_testjni_MyJNI_sayhello
        (JNIEnv *env, jclass obj){
    //返回一句话
    return (*env)->NewStringUTF(env, "JNI I am xiaoluo");
}

#ifdef __cplusplus
}
#endif
#endif
